Update issue templates
## `Bug Report Section`

### 1. Your Platform

[ ] iOS <br/>
[ ] Android <br/>
[ ] React Native <br/>
[ ] Flutter <br/>
[ ] React <br/>
[ ] Vanila JS <br/>
[ ] GTM <br/>

### 2. SDK Version

e.g. 1.0.0

### 3. Issue Description

e.g. I can't build the project because of the following error.

```
Error: Undefined symbol: _OBJC_CLASS_$_Notifly
```

### 4. Steps to reproduce the issue

e.g. My Podfile is as follows.

```
Your Podfile
```

i got the error above when `pod install` and then `build` the project.

### 5. (Build issue only) Do you try to build and run the example project with your environment?

[ ] Yes
[ ] No

#### If you answered "Yes", please describe the result.

#### If you answered "No", please try it first.